version: '3.6'

services:
  api:
    build: .
    ports: "3000:3000"
    links:
      - "db:psql1"

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev