version: '3.6'

services:
  
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 8081:27017
    networks:
      - network1
    volumes:
      - mongo_volum

  indication_api:
    build: .
    ports:
      - 50051:50051

networks:
  network1:
    external: true
    name: app_network

volumes:
  mongo_volum: